config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :bunkers do
    collection do
      get 'index_host', as: "host"
    end
    resources :trips, only: [:new, :create]
    resources :reviews, only: :create
  end


  resources :trips, only: [:update, :edit, :destroy, :show, :index] do
    member do
      get 'confirmation'
      patch 'approve'
    end
  end

  resources :conversations do
    resources :messages
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-rocket"></i> in a bunker
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="<%= yield(:sticky_navbar).blank? ? 'navbar-wagon-sticky' : yield(:sticky_navbar) %> navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "newlogo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Links -->
    <% if user_signed_in? %>

      <form action="<%= bunkers_path %>" class="form-inline">
        <input type="text" name="query" placeholder="&nbsp Search for Bunkers">
      </form>

      <%= link_to "List Your Bunker", new_bunker_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%#= link_to "Bunkers", bunkers_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", trips_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", conversations_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <%= image_tag facebook_image(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <!-- <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <%# end %>
            </li> -->
            <!-- <li>
              <%#= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <%# end %>
            </li> -->
             <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
            <li>
              <%= link_to host_bunkers_path do %>
                <i class="fa fa-superpowers"> Host Interface</i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <strong>Sign in</strong>
      <% end %>
      <%= link_to new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <strong>Register</strong>
      <% end %>
    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "List a Bunker", new_bunker_path %></li>
        <li><%= link_to "Trips", trips_path %></li>
        <li><%= link_to "Messages", conversations_path %></li>
      </ul>
    </div>
  </div>
</div>