config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :bunkers do
    collection do
      get 'index_host', as: "host"
    end
    resources :trips, only: [:new, :create]
    resources :reviews, only: :create
  end


  resources :trips, only: [:update, :edit, :destroy, :show, :index] do
    member do
      get 'confirmation'
      patch 'approve'
    end
  end

  resources :conversations do
    resources :messages
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

end

app/models/bunker.rb
class Bunker < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_attachments :photos, maximum: 10
  has_many :trips, dependent: :destroy
  has_and_belongs_to_many :features
  has_many :reviews, dependent: :destroy
  validates :price, :size, :name, :description, :address, presence: true, allow_blank: false

  # don't forget to add user
  # geocoded_by :location
  # after_validation :geocode, if: :location_changed?

  def self.search(query)
    if query.present?
      query = query.downcase
      Bunker.joins(:user).where("lower(bunkers.name) LIKE ? OR
                                           lower(users.first_name) LIKE ? OR
                                           lower(users.last_name) LIKE ?",
                                           "%#{query}%",
                                           "%#{query}%",
                                           "%#{query}%")
    else
      Bunker.all
    end
  end
end

app/controllers/bunkers_controller.rb
class BunkersController < ApplicationController
  before_action :set_bunker, only: [:show, :edit, :update, :destroy]
  # GET /bunkers
  # GET /bunkers.json
  def index
    @bunkers = Bunker.search(params[:query])

    @markers = Gmaps4rails.build_markers(@bunkers) do |bunker, marker|
      marker.lat bunker.latitude
      marker.lng bunker.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end

  def index_host
    @user = current_user
    @bunkers = current_user.bunkers
  end
  # GET /bunkers/1
  # GET /bunkers/1.json
  def show
    bunkers = [@bunker]
    @markers = Gmaps4rails.build_markers(bunkers) do |bunker, marker|
      marker.lat bunker.latitude
      marker.lng bunker.longitude
    end
    @user = current_user
    @review = Review.new
  end

  # GET /bunkers/new
  def new
    @bunker = Bunker.new
    # @bunker.build_location
  end

  # GET /bunkers/1/edit
  def edit
  end

  # POST /bunkers
  # POST /bunkers.json
  def create
    @bunker = Bunker.new(bunker_params)
    @bunker.user = current_user
    respond_to do |format|
      if @bunker.save
        format.html { redirect_to @bunker, notice: 'Bunker was successfully created.' }
        format.json { render :show, status: :created, location: @bunker }
      else
        format.html { render :new }
        format.json { render json: @bunker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bunkers/1
  # PATCH/PUT /bunkers/1.json
  def update
    respond_to do |format|
      if @bunker.update(bunker_params)
        format.html { redirect_to @bunker, notice: 'Bunker was successfully updated.' }
        format.json { render :show, status: :ok, location: @bunker }
      else
        format.html { render :edit }
        format.json { render json: @bunker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bunkers/1
  # DELETE /bunkers/1.json
  def destroy
    @bunker.destroy
    respond_to do |format|
      format.html { redirect_to bunkers_url, notice: 'Bunker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bunker
      @bunker = Bunker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bunker_params
      params.require(:bunker).permit(:description, :address, :name, :user, :price, :size, photos: [], feature_ids: [])
    end
end

app/views/bunkers/_features_set.html.erb
  <% @bunker.features.each do |feature| %>
    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-6">
      <div class="listing_item">
        <i class="fa <%= feature.fa_icon %> icon" aria-hidden="true"></i>
        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><%= feature.name %></font></font></h5>
        <p class="light sm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><%= feature.description %></font></font></p>
      </div>
    </div>
  <% end %>

app/views/bunkers/_form.html.erb
<br>
<div class="container">
  <div class="row">
    <%= simple_form_for(@bunker) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :detailed_description %>
        <%= f.input :price %>
        <%= f.input :size %>
        <%#= f.collection_check_boxes :options, [[true, 'Yes'] ,[false, 'No']], :first, :last %>
        <%= f.input :address %>
        <%= f.input :zip_code, as: :string %>
        <%= f.input :city %>
        <%= f.input :country, priority: [ 'US' ] %>
        <%= f.collection_check_boxes :feature_ids, Feature.all, :id, :name %>
      </div>
        <%= f.input :photos, as: :attachinary %>

        <div class="form-actions text-center">
          <%= f.button :submit %>
        </div>
    <% end %>
  </div>
</div>


<%#= f.simple_fields_for :location do |l| %>
          <%#= l.country_select :country, { priority_countries: ["GB", "FR", "US", "BR"] }, {class: "form-control"} %>
        <%# end %>

app/views/bunkers/_picture_carousel.html.erb
<div class="container-fluid">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @bunker.photos.each_with_index do |photo, index| %>
      <% end  %>
    </ol>

    <div class="carousel-inner">
      <% @bunker.photos.each_with_index do |photo, index| %>
      <div class="item<%= " active" if index == 0 %>">
        <%= cl_image_tag photo.path %>
      </div>
      <% end %>
    </div>

    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<style>
  .carousel-inner > .item > img, .carousel-inner > .item > a > img {
    width: 100%;
    max-height: 400px;
  }

  .container-fluid {
    padding-left: 0;
    padding-right: 0;
  }

.carousel-indicators .active {
  height:0px;
  opacity: 0%;
  outline: none;
}
</style>

app/views/bunkers/_review.html.erb
<div id="reviews">
          <h4>Reviews</h4>
  <% if @bunker.reviews.empty? %>
    Be the first to leave a review for <%= @bunker.name %>
  <% else %>
    <% @bunker.reviews.each do |review| %>
      <%= render 'reviews/show', review: review %>
    <% end %>
  <% end %>
</div>

app/views/bunkers/_sticky_menu.html.erb
<div id="sticker-sticky-wrapper" class="sticky-wrapper hey">
  <div class="sticky-header">
    <div id="dynamic-menu-bar">

      <div id="dynamic-menu-section">
        <span style="opacity: 1; cursor: pointer;">
          <a href="#DescriptionFor">
            <div id="dynamic-menu-item">
              <span id="dynamic-menu-span">Description</span>
            </div>
          </a>
        </span>
      </div>

      <div id="dynamic-menu-section">
        <span style="opacity: 1; cursor: pointer;">
          <a href="#LocationFor">
            <div id="dynamic-menu-item">
              <span id="dynamic-menu-span">Location</span>
            </div>
          </a>
        </span>
      </div>

      <div id="dynamic-menu-section">
        <span style="opacity: 1; cursor: pointer;">
          <a href="#FeaturesFor">
          <div id="dynamic-menu-item">
            <span id="dynamic-menu-span">Features</span>
          </div>
        </a>
      </span>
    </div>


    <div id="dynamic-menu-section">
      <span style="opacity: 1; cursor: pointer;">
        <a href="#SpecificationsFor">
        <div id="dynamic-menu-item">
          <span id="dynamic-menu-span">Specifications</span>
        </div>
      </a>
    </span>
  </div>

  <div id="dynamic-menu-section">
    <span style="opacity: 1; cursor: pointer;">
      <div id="dynamic-menu-item-strong">
        <span id="dynamic-menu-span">
          <% if @bunker.user.id != current_user.id %>
            <%= link_to 'Message Host', conversations_path(sender_id: current_user.id, recipient_id: @bunker.user.id), method: :post %>
          <% end %>
          </span>
        </div>
    </span>
  </div>

<div id="dynamic-menu-section">
  <span style="opacity: 1; cursor: pointer;">
 <div id="dynamic-menu-item-strong">
        <span id="dynamic-menu-span"><%= link_to "Book Now", new_bunker_trip_path(@bunker) %></span>
      </div>
  </span>
</div>

</div>
</div>
</div>


<!-- { :class => "btn-default text-center" }
 -->

app/views/bunkers/booking.html.erb
<div class="container">
  <h2>Congrats <%= current_user.first_name %>, you are one step closer to survival.</h2>
  <h3> Your Booking: <%= link_to @bunker.name, bunker_path(@bunker) %> in <%= @bunker.country %></h3>

  <div class="row">
    <%= simple_form_for [@bunker, @trip] do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :first_name, input_html: { value: current_user&.first_name } %>
      <%= f.input :last_name, input_html: { value: current_user&.last_name } %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <div class="form-actions text-center">
        <%= f.button :submit, 'Book Your Bunker' %>
      </div>
    </div>
    <% end %>
  </div>

  <%= link_to "Back to Bunker", bunker_path(@bunker) %>
</div>

app/views/bunkers/edit.html.erb
<h1>Editing Bunker</h1>

<%= render 'form', bunker: @bunker %>

<%= link_to 'Show', @bunker %> |
<%= link_to 'Back', bunkers_path %>

app/views/bunkers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-8 col-xs-6">

        <center> <h1 class="highlight">Bunkers</h1></center>

        <div class="row">
          <% @bunkers.each do |bunker| %>
          <div class="col-l-4 col-xs-4 col-sm-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bunker.photos[0].path if bunker.photos.any? %>');">
              <div class="card-category"><%= bunker.latitude %>, <%= bunker.longitude %></div>
              <div class="card-description">
                <h2><%= bunker.name %></h2>
                <p style="align">$<%= bunker.price %>/DAY</p>
              </div>
              <%= image_tag facebook_image(bunker.user), class: "card-user" %>
              <%= link_to '', bunker_path(bunker), class: 'card-link' %>
            </div>
            <br>
          </div>
          <%end %>

        </div>
        <center><%= link_to "List Your Bunker", new_bunker_path, :class => "button" %></center>
        <br>
      </div>
      <div class="col-lg-4 col-xs-6">
        <div id="map" style="width: 100%; height: 540px;"></div>

        <% content_for(:after_js) do %>
        <%= javascript_tag do %>
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
  <% end %>
  <% end %>
</div>
</div>
</div>
</div>
<!--
 <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBS9JD0vndn2mIVlsNo4r_CQbo1W024W60&callback=initMap"
  type="text/javascript"></script>  -->

app/views/bunkers/index_host.html.erb
<div class="wrapper">
  <br>
  <br>
  <p id="notice"><%= notice %></p>


  <div class="container">
    <br>
    <center> <h3>Your Bunkers</h3></center>
    <br>
    <div class="row">
      <% @bunkers.each do |bunker| %>
      <div class="col-l-4 col-xs-4 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bunker.photos[0].path %>');">
          <div class="card-category"><%= bunker.country %></div>
          <div class="card-description">
            <h2><%= bunker.name %></h2>
            <p style="align">$<%= bunker.price %>/DAY</p>
          </div>
          <%= image_tag facebook_image(bunker.user), class: "card-user" %>
          <%= link_to '', bunker_path(bunker), class: 'card-link' %>
        </div>
      </div>
      <%end %>
    </div>
    <center> <h3>Upcoming Trips At Your Bunkers</h3></center>
    <div class="row">
      <% @bunkers.each do |bunker| %>
      <% bunker.trips.each do |trip| %>
      <% if trip.approved == true %>
      <div class="col-l-4 col-xs-4 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path trip.bunker.photos[0].path %>');">
          <div class="card-category"><%= trip.bunker.country %></div>
          <div class="card-description">
            <h2><%= trip.bunker.name %></h2>
            <p style="align"><%= trip.start_date %></p>
            <p><%= trip.approved ? "Approved" : "Pending" %></p>
          </div>
          <%= link_to '', trip_path(trip), class: 'card-link' %>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
    </div>

    <center> <h3>Trips Awaiting Approval</h3></center>
    <div class="row">
      <% @bunkers.each do |bunker| %>
      <% bunker.trips.each do |trip| %>
      <% if trip.approved == false %>
      <div class="col-l-4 col-xs-4 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path trip.bunker.photos[0].path %>');">
          <div class="card-category"><%= trip.bunker.country %></div>
          <div class="card-description">
            <h2><%= trip.bunker.name %></h2>
            <p style="align"><%= trip.start_date %></p>
            <p><%= trip.approved ? "Approved" : "Pending" %></p>
          </div>
          <%= link_to '', approve_trip_path(trip, approved: true), method: :patch, class: 'card-link' %>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bunkers/new.html.erb
<center><h1 class=highlight>New Bunker</h1></center>
<%= render 'form', bunker: @bunker %>
<br>
<br>
<br>

app/views/bunkers/show.html.erb
<% content_for(:sticky_navbar) do %>
  'none'
<% end %>

<!-- Carousel -->

<%= render 'picture_carousel' %>

<!-- Sticky Header Menu -->

<%= render 'sticky_menu' %>


<!-- Description of Bunker -->

<div class="container">
  <div class="page-header">
    <center><h1 class="highlight"><%= @bunker.name %> </center>
      <center><h4><%= @bunker.description%></h4> </center>
      <br>


 <!-- Specs of Bunker -->

    <div class="row" id="SpecificationsFor">
      <h4>Bunker Specs</h4>
      <p><strong id="heavy">Additional Information: </strong> <%= @bunker.detailed_description %></p>
      <p><strong id="heavy">Price: </strong> $<%= @bunker.price %>/night</p>
      <p><strong id="heavy">Size: </strong><%= @bunker.size %>m²</p>
    </div>

 <!-- Features of Bunker -->
 <br>

 <div class="row" id="FeaturesFor">
  <h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">What you get</font></font></h4>
    <%= render 'features_set' %>
  </div>
</div>
<!-- Location -->

    <div class="row" id="LocationFor">
      <h4>Where is it</h4>
      <div id="map" style="width: 100%; height: 600px;"></div>
    </div>
  </div>
</div>

<!-- Reviews -->
<div class="row">
  <%= render 'review' %>
</div>
<div class="row">
  <%= render 'reviews/form', bunker: @bunker, review: @review %>
</div>
<!-- Links and Footer -->

<center><%= link_to 'View More Bunkers |', bunkers_path %>
<% if @bunker.user == @user %>
        <%= link_to 'Edit', edit_bunker_path(@bunker) %>
<% end %>
</center>
<br>
<br>
<% content_for(:after_js) do %>
        <%= javascript_tag do %>
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
  <% end %>
  <% end %>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    $("#sticker-sticky-wrapper").sticky({topSpacing:0, className: "is-sticky hey"});
  });
</script>
<% end %>